#!/bin/bash


clear
NOWF=$(date +"%d-%m-%Y %T")
echo Time $NOWF
echo "Текущий каталог " $PWD
echo Time $NOWF>>log/log.txt

export GOPATH=$PWD
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin
export CGO_ENABLED=0


echo load gorn
go get github.com/jinzhu/gorm

echo load sqllite
go get github.com/jinzhu/gorm/dialects/sqlite

echo Finish...