#!/bin/bash

#while read LINE; do echo "$LINE" | cut -f1 -d":"; done < /etc/passwd

# http://freaksidea.com/show-48-uchimsia-proghrammirovat-v-shell-i-o-pereadresatsiia-chast-2
while read line;do echo $line; done < tmp/bla

#> /tmp/bla